version: '3'
services: 
  postgres:
    image: 'postgres:alpine'
  redis:
    image: 'redis:alpine'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgres_password
      - PG_PORT=5432
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /usr/app/node_modules
      - ./client:/usr/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  nginx:
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports: 
      - '80:80'